apiVersion: 2024-08-02-preview
type: Microsoft.App/containerApps
name: grafana
location: northeurope
properties:
  managedEnvironmentId: /subscriptions/5e58abe7-2302-449a-a7a2-35f2b3c4b886/resourceGroups/iiot-poc-rg/providers/Microsoft.App/managedEnvironments/iiot-env-public

  configuration:
    activeRevisionsMode: Single
    ingress:
      external: true
      targetPort: 3000
      transport: auto
      allowInsecure: false
      traffic:
        - latestRevision: true
          weight: 100
    # Ingen ACR behövs när vi använder officiell bild

  template:
    containers:
      - name: grafana
        image: grafana/grafana:10.4.2
        env:
          - name: GF_SECURITY_ADMIN_USER
            value: admin
          - name: GF_SECURITY_ADMIN_PASSWORD
            secretRef: grafana-admin-password
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Viewer
          - name: GF_USERS_ALLOW_SIGN_UP
            value: "false"
          - name: GF_SERVER_HTTP_PORT
            value: "3000"
        probes:
          - type: liveness
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          - type: readiness
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
        volumeMounts:
          - volumeName: grafana-data
            mountPath: /var/lib/grafana  # grafana.db (SQLite) -> EmptyDir för att undvika SMB-lås
    volumes:
      - name: grafana-data
        storageType: EmptyDir

    scale:
      minReplicas: 1
      maxReplicas: 1
