apiVersion: 2024-08-02-preview
type: Microsoft.App/containerApps
name: grafana
location: North Europe

properties:
  managedEnvironmentId: /subscriptions/5e58abe7-2302-449a-a7a2-35f2b3c4b886/resourceGroups/iiot-poc-rg/providers/Microsoft.App/managedEnvironments/iiot-env-public

  configuration:
    activeRevisionsMode: Single
    ingress:
      external: true
      targetPort: 3000
      allowInsecure: false
      traffic:
        - latestRevision: true
          weight: 100

  template:
    revisionSuffix: "vol-002"
    containers:
      - name: grafana
        image: grafana/grafana:10.4.2
        env:
          - name: GF_SECURITY_ADMIN_USER
            value: admin
          - name: GF_SECURITY_ADMIN_PASSWORD
            secretRef: grafana-admin-password
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Viewer
          - name: GF_USERS_ALLOW_SIGN_UP
            value: "false"
          - name: GF_SERVER_HTTP_PORT
            value: "3000"
        volumeMounts:
          - volumeName: grafana-data
            mountPath: /var/lib/grafana
          - volumeName: grafana-provisioning
            mountPath: /etc/grafana/provisioning
    volumes:
      - name: grafana-data
        storageType: AzureFile
        storageName: grafana-storage                # välj din faktiska storage
      - name: grafana-provisioning
        storageType: AzureFile
        storageName: grafana-provisioning-storage   # välj din faktiska storage

    scale:
      minReplicas: 1
      maxReplicas: 1
