type: Microsoft.App/containerApps
name: iiot-fft-service
properties:
  environmentId: /subscriptions/5e58abe7-2302-449a-a7a2-35f2b3c4b886/resourceGroups/iiot-poc-rg/providers/Microsoft.App/managedEnvironments/iiot-env-public
  configuration:
    ingress: null
  template:
    containers:
      - name: iiot-fft-service
        image: iiotpocacr.azurecr.io/iiot-fft-service:__TAG__
        probes:
          - type: Liveness
            httpGet: { path: /health, port: 5000 }
            initialDelaySeconds: 3
            periodSeconds: 10
          - type: Readiness
            httpGet: { path: /health, port: 5000 }
            initialDelaySeconds: 3
            periodSeconds: 5
