type: Microsoft.App/containerApps
name: iiot-telegraf
properties:
  environmentId: /subscriptions/5e58abe7-2302-449a-a7a2-35f2b3c4b886/resourceGroups/iiot-poc-rg/providers/Microsoft.App/managedEnvironments/iiot-env-public
  configuration:
    activeRevisionsMode: Single
    # No ingress (not serving traffic) – probes går ändå direkt mot containern
  template:
    containers:
      - name: iiot-telegraf
        image: iiotpocacr.azurecr.io/iiot-telegraf:__TAG__
        env:
          - name: MQTT_URL
            value: tcp://iiot-mosquitto:1883
          - name: MQTT_TOPIC
            value: sensors/#

          - name: INFLUX_URL
            value: http://iiot-influxdb:8086
          - name: INFLUX_ORG
            value: iiot
          - name: INFLUX_BUCKET
            value: vibration
          - name: INFLUX_TOKEN
            secretRef: influxdb-admin-token

        volumeMounts:
          - volumeName: telegraf-config
            mountPath: /etc/telegraf
        probes:
          - type: liveness
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          - type: readiness
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
    volumes:
      - name: telegraf-config
        storageType: AzureFile
        storageName: iiotdata-storage
