apiVersion: 2024-08-02-preview
type: Microsoft.App/containerApps
name: iiot-fft-service
location: northeurope

properties:
  managedEnvironmentId: /subscriptions/5e58abe7-2302-449a-a7a2-35f2b3c4b886/resourceGroups/iiot-poc-rg/providers/Microsoft.App/managedEnvironments/iiot-env-public

  configuration:
    activeRevisionsMode: Single
    ingress:
      external: false
      targetPort: 0
      allowInsecure: false

  template:
    containers:
      - name: iiot-fft-service
        image: iiotpocacr.azurecr.io/iiot-fft-service:latest  # workflow kan override:a med SHA
        env:
          # MQTT (intern mosquitto)
          - name: MQTT_HOST
            value: mosquitto.internal.happyisland-fa52694f.northeurope.azurecontainerapps.io
          - name: MQTT_PORT
            value: "1883"
          - name: MQTT_TOPIC_IN
            value: iiot/vibration_raw
          - name: MQTT_TOPIC_OUT
            value: iiot/vibration_fft
          - name: SAMPLE_RATE
            value: "25600"

          # InfluxDB
          - name: INFLUXDB_URL
            value: http://influxdb:8086
          - name: INFLUXDB_ORG
            value: iiot-org
          - name: INFLUXDB_BUCKET
            value: iiot
          - name: INFLUXDB_TOKEN
            secretRef: influxdb-admin-token   # <— VIKTIGT: använd 'secretRef' (inte value/valueFromSecret)

          # Modell
          - name: MODEL_PATH
            value: /models/iforest_final.joblib

        resources:
          cpu: 0.5
          memory: 1Gi

        volumeMounts:
          - volumeName: fft-storage
            mountPath: /models
            # readOnly: true   # aktivera när du vill låsa mounten

    volumes:
      - name: fft-storage
        storageType: AzureFile
        storageName: fft-storage

    scale:
      minReplicas: 1
      maxReplicas: 1
