apiVersion: 2024-08-02-preview
type: Microsoft.App/containerApps
name: feature-service
location: northeurope
properties:
  managedEnvironmentId: /subscriptions/5e58abe7-2302-449a-a7a2-35f2b3c4b886/resourceGroups/iiot-poc-rg/providers/Microsoft.App/managedEnvironments/iiot-env-public
  configuration:
    activeRevisionsMode: Single
  template:
    containers:
      - name: feature-service
        image: iiotpocacr.azurecr.io/feature-service:latest
        env:
          - name: INFLUX_URL
            value: http://influxdb:8086
          - name: INFLUX_ORG
            value: iiot
          - name: BUCKET_RAW
            value: machine_health
          - name: BUCKET_FEATURES
            value: features
          - name: INFLUX_TOKEN
            secretRef: influxdb-admin-token
    scale:
      minReplicas: 1
      maxReplicas: 1
