type: Microsoft.App/containerApps
name: mosquitto
location: northeurope
properties:
  managedEnvironmentId: /subscriptions/5e58abe7-2302-449a-a7a2-35f2b3c4b886/resourceGroups/iiot-poc-rg/providers/Microsoft.App/managedEnvironments/iiot-env-public
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: false            # sätt true om du vill nås externt (kräver VNET för TCP)
      targetPort: 1883
      transport: tcp
      traffic:
        - latestRevision: true
          weight: 100
    # 🔐 deklarera secret här (värdet sätts via CLI/Workflow – inte i filen)
    secrets:
      - name: mosqconf
        value: ""                # lämna tomt i git; fylls via az containerapp secret set
  template:
    containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0  # stabil publikt tag; byt till din ACR-bild när du vill
        env:
          - name: TZ
            value: UTC
        command:
          - /usr/sbin/mosquitto
        args:
          - -c
          - /appconfig/mosquitto.conf
          - -v
        volumeMounts:
          # ✅ montera ENDAST data-katalogen på Azure Files
          - volumeName: mosquitto-data
            mountPath: /mosquitto/data
          # ✅ montera secret som FIL-katalog, inte över /mosquitto/config
          - volumeName: mosqconfvol
            mountPath: /appconfig
        probes:
          - type: Liveness
            tcpSocket:
              port: 1883
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          - type: Readiness
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 10
    volumes:
      # 🗂️ Azure Files (data)
      - name: mosquitto-data
        storageType: AzureFile
        storageName: mosquitto-data-storage
      # 🔐 Secret-volym för konfigfilen
      - name: mosqconfvol
        secret:
          secretRef: mosqconf
