type: Microsoft.App/containerApps
apiVersion: 2023-08-01
name: mosquitto
location: northeurope
properties:
  managedEnvironmentId: /subscriptions/5e58abe7-2302-449a-a7a2-35f2b3c4b886/resourceGroups/iiot-poc-rg/providers/Microsoft.App/managedEnvironments/iiot-env-public
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: false            # sätt true om du vill nås externt (kräver VNET för TCP i många konfigurationer)
      targetPort: 1883
      transport: tcp
      traffic:
        - latestRevision: true
          weight: 100
    # 🔐 deklarera secret här (värdet sätts via CLI/Workflow – inte i filen)
    secrets:
      - name: mosqconf
        value: ""                # lämna tomt i git; fylls via az containerapp secret set
  template:
    containers:
      - name: mosquitto
        image: __IMAGE__         # placeholder — ersätt via CI (workflow gör sed/replace)
        env:
          - name: TZ
            value: UTC
        # Kör mosquitto med din konfig-fil som mountas som fil i /appconfig
        command:
          - /usr/sbin/mosquitto
        args:
          - -c
          - /appconfig/mosquitto.conf
          - -v
        resources:
          cpu: 0.5
          memory: 1.0Gi
        volumeMounts:
          # ✅ montera ENDAST data-katalogen på Azure Files
          - volumeName: mosquitto-data
            mountPath: /mosquitto/data
          # 🔐 montera secret som FIL-katalog (innehåller mosquitto.conf)
          - volumeName: mosqconfvol
            mountPath: /appconfig
        probes:
          - type: Liveness
            tcpSocket:
              port: 1883
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          - type: Readiness
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 10
    scale:
      minReplicas: 1
      maxReplicas: 1
    volumes:
      # 🗂️ Azure Files (data) — storageName måste existera som en storage binding i Managed Environment
      - name: mosquitto-data
        storageType: AzureFile
        storageName: mosquitto-data-storage
      # 🔐 Secret-volym för konfigfilen (refererar till secrets.name ovan)
      - name: mosqconfvol
        secret:
          secretRef: mosqconf
