name: Auto deploy feature_service

on:
  push:
    branches: [ main ]
    paths:
      - 'feature_service/**'
      - 'infra/iiot-feature-service.yaml'
      - '.github/workflows/iiot-feature-AutoDeploy.yml'
  workflow_dispatch:

# Hindra parallella körningar som krockar
concurrency:
  group: feature-service
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.IIOTFFTSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IIOTFFTSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IIOTFFTSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login -n iiotpocacr

      - name: Build & push image to ACR
        run: |
          REPO=iiotpocacr.azurecr.io/feature-service   # <— OBS: bindestreck. Byt till feature_service om ditt ACR-repo heter så.
          docker build -f feature_service/Dockerfile -t $REPO:${{ github.sha }} -t $REPO:latest feature_service
          docker push $REPO:${{ github.sha }}
          docker push $REPO:latest
          echo "IMAGE=$REPO:${{ github.sha }}" >> $GITHUB_ENV
          

      # Deploy via YAML + sätt app-secrets här (ingen separat CLI, ingen race)
      - name: Deploy feature-service (YAML)
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: iiot-poc-rg
          containerAppName: feature-service
          yamlConfigPath: infra/iiot-feature-service.yaml
          imageToDeploy: ${{ env.IMAGE }}
          secrets: |
            influxdb-admin-token=${{ secrets.INFLUXDB_ADMIN_TOKEN }}
          disableTelemetry: false

      # (Valfritt) städa inaktiva revisioner
      - name: Cleanup old inactive revisions
        run: |
          az extension add -n containerapp --upgrade
          az containerapp revision list -g iiot-poc-rg -n feature-service \
            --query "[?properties.active==\`false\`].name" -o tsv | \
          xargs -r -I {} az containerapp revision delete \
            -g iiot-poc-rg -n feature-service --revision {} --yes
