name: Trigger auto deployment for iiot-fft-service
on:
  push:
    branches: [ main ]
    paths:
      - 'fft_service/**'
      - 'infra/iiot-fft-service.yaml'
      - '.github/workflows/iiot-fft-service-AutoDeployTrigger.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.IIOTFFTSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IIOTFFTSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IIOTFFTSERVICE_AZURE_SUBSCRIPTION_ID }}
      - name: Render infra YAML with image tag
        run: |
          cp infra/iiot-fft-service.yaml infra/iiot-fft-service.rendered.yaml
          sed -i "s|__TAG__|${{ github.sha }}|g" infra/iiot-fft-service.rendered.yaml
          cat infra/iiot-fft-service.rendered.yaml
      - name: Build and deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/fft_service
          dockerfilePath: Dockerfile
          acrName: iiotpocacr
          containerAppName: iiot-fft-service
          resourceGroup: iiot-poc-rg
          imageToBuild: iiotpocacr.azurecr.io/iiot-fft-service:${{ github.sha }}
          yamlConfigPath: infra/iiot-fft-service.rendered.yaml
      - name: Clean up old inactive revisions
        run: |
          az containerapp revision list \
            -g iiot-poc-rg -n iiot-fft-service \
            --query "[?properties.active==\`false\`].name" -o tsv | \
          xargs -r -I {} az containerapp revision delete \
            -g iiot-poc-rg -n iiot-fft-service --revision {} --yes
