name: Auto deploy influxdb

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/influxdb.yaml'
      - '.github/workflows/iiot-influxdb-AutoDeploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.IIOTFFTSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IIOTFFTSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IIOTFFTSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Sanity check
        run: |
          az account show -o table
          az containerapp list -g iiot-poc-rg -o table

      - name: Deploy InfluxDB (ACA via YAML)
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: iiot-poc-rg
          containerAppName: influxdb
          containerAppEnvironment: iiot-env-public
          yamlConfigPath: infra/influxdb.yaml   # YAML äger imagen & volymer

      - name: Cleanup old inactive revisions
        run: |
          az containerapp revision list -g iiot-poc-rg -n influxdb \
            --query "[?properties.active==\`false\`].name" -o tsv | \
          xargs -r -I {} az containerapp revision delete \
            -g iiot-poc-rg -n influxdb --revision {} --yes
