name: Auto deploy iiot-fft-service
on:
  push:
    branches: [ main ]
    paths:
      - 'fft_service/**'
      - 'infra/iiot-fft-service.yaml'
      - '.github/workflows/iiot-fft-service-AutoDeployTrigger.yml'
  workflow_dispatch:

concurrency:
  group: iiot-fft-service-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      id-token: write
      contents: read

    env:
      REPO: iiotpocacr.azurecr.io/iiot-fft-service
      IMAGE_SHA: iiotpocacr.azurecr.io/iiot-fft-service:${{ github.sha }}
      IMAGE_LATEST: iiotpocacr.azurecr.io/iiot-fft-service:latest

    steps:
      - uses: actions/checkout@v4

      # Login to Azure (OIDC)
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.IIOTFFTSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IIOTFFTSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IIOTFFTSERVICE_AZURE_SUBSCRIPTION_ID }}

      # Login to ACR (manual push)
      - name: ACR login
        run: az acr login --name iiotpocacr

      # Build & push both SHA and latest
      - name: Build (SHA + latest) and push
        working-directory: fft_service
        run: |
          docker build -f Dockerfile -t "$IMAGE_SHA" -t "$IMAGE_LATEST" .
          docker push "$IMAGE_SHA"
          docker push "$IMAGE_LATEST"

      # Render infra YAML (only if placeholders exist)
      - name: Render infra YAML with image
        run: |
          cp infra/iiot-fft-service.yaml infra/iiot-fft-service.rendered.yaml
          sed -i "s|__IMAGE__|$IMAGE_SHA|g" infra/iiot-fft-service.rendered.yaml || true
          sed -i "s|__TAG__|${{ github.sha }}|g" infra/iiot-fft-service.rendered.yaml || true
          cat infra/iiot-fft-service.rendered.yaml

      # Deploy using the previously pushed image
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: iiot-poc-rg
          containerAppName: iiot-fft-service
          imageToDeploy: ${{ env.IMAGE_SHA }}
          yamlConfigPath: infra/iiot-fft-service.rendered.yaml
          waitForRollout: false
          # secrets: |
          #   EXAMPLE_SECRET=${{ secrets.EXAMPLE_SECRET }}

      - name: Clean up old inactive revisions
        run: |
          az containerapp revision list \
            -g iiot-poc-rg -n iiot-fft-service \
            --query "[?properties.active==\`false\`].name" -o tsv | \
          xargs -r -I {} az containerapp revision delete \
            -g iiot-poc-rg -n iiot-fft-service --revision {} --yes
