name: Auto deploy telegraf

on:
  push:
    branches: [ main ]
    paths:
      - 'telegraf/**'
      - 'infra/telegraf.yaml'
      - '.github/workflows/telegraf-AutoDeploy.yml'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      RG: iiot-poc-rg
      APP: telegraf
      ENV_NAME: iiot-env-public
      ACR_NAME: iiotpocacr

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.IIOTFFTSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IIOTFFTSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IIOTFFTSERVICE_AZURE_SUBSCRIPTION_ID }}

      # Create app once (internal) so MI exists before configuring registry
      - name: Ensure app exists (first run)
        shell: bash
        run: |
          az containerapp show -g "$RG" -n "$APP" >/dev/null 2>&1 || \
          az containerapp create -g "$RG" -n "$APP" \
            --environment "$ENV_NAME" \
            --image mcr.microsoft.com/azuredocs/containerapps-helloworld:latest \
            --ingress internal

      # Wait until system-assigned identity is issued
      - name: Wait for system identity to be ready
        shell: bash
        run: |
          set -euo pipefail
          for i in {1..30}; do
            PID=$(az containerapp show -g "$RG" -n "$APP" --query "identity.principalId" -o tsv || true)
            if [ -n "${PID:-}" ] && [ "$PID" != "None" ]; then
              echo "System MI principalId: $PID"; break
            fi
            echo "Waiting for system MI..."; sleep 5
            if [ $i -eq 30 ]; then echo "Timeout waiting for MI"; exit 1; fi
          done

      # Bind ACR to app using system identity (AcrPull must already be granted to env/app MI)
      - name: Configure ACR registry with system identity
        shell: bash
        run: |
          ACR_SERVER="${ACR_NAME}.azurecr.io"
          az containerapp identity assign -g "$RG" -n "$APP" --system-assigned
          az containerapp registry set -g "$RG" -n "$APP" --server "$ACR_SERVER" --identity system

      # Use Key Vault secret reference (preferred) OR GitHub secret fallback
      - name: Ensure KV secret reference (influxdb-admin-token) exists
        if: ${{ vars.SECRET_SOURCE == 'kv' }}
        shell: bash
        env:
          KV_INFLUX_TOKEN_URL: https://iiotpockv.vault.azure.net/secrets/influxdb-admin-token
        run: |
          set -euo pipefail
          for i in {1..12}; do
            if az containerapp secret set \
              -g "$RG" -n "$APP" \
              --secrets influxdb-admin-token=keyvaultref:${KV_INFLUX_TOKEN_URL},identityref:system; then
              echo "KV secret reference added."
              exit 0
            fi
            echo "Retry $i/12 adding KV secret reference..."; sleep 10
          done
          echo "Failed to add KV secret reference"; exit 1

      - name: Validate required secret (GitHub fallback)
        if: ${{ vars.SECRET_SOURCE != 'kv' }}
        shell: bash
        run: |
          TOK='${{ secrets.INFLUXDB_ADMIN_TOKEN }}'
          if [ -z "$TOK" ]; then
            echo "Missing secret: INFLUXDB_ADMIN_TOKEN"; exit 1
          fi
          echo "INFLUXDB_ADMIN_TOKEN length: ${#TOK}"

      - name: Set app secrets (GitHub fallback)
        if: ${{ vars.SECRET_SOURCE != 'kv' }}
        shell: bash
        run: |
          CLEAN_TOKEN="$(printf '%s' '${{ secrets.INFLUXDB_ADMIN_TOKEN }}' | tr -d '\r\n')"
          az containerapp secret set -g "$RG" -n "$APP" \
            --secrets influxdb-admin-token="$CLEAN_TOKEN"

      - name: Render YAML (image tag + registry)
        run: |
          cp infra/telegraf.yaml infra/telegraf.rendered.yaml
          sed -i "s|__TAG__|${{ github.sha }}|g" infra/telegraf.rendered.yaml
          sed -i "s|__ACR__|${{ env.ACR_NAME }}.azurecr.io|g" infra/telegraf.rendered.yaml
          echo "Rendered image line(s):"
          grep -n 'image:' infra/telegraf.rendered.yaml

      - name: Build & Deploy Telegraf (ACA)
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/telegraf
          dockerfilePath: Dockerfile
          acrName: ${{ env.ACR_NAME }}
          containerAppName: ${{ env.APP }}
          resourceGroup: ${{ env.RG }}
          containerAppEnvironment: ${{ env.ENV_NAME }}
          imageToBuild: ${{ env.ACR_NAME }}.azurecr.io/iiot-telegraf:${{ github.sha }}
          yamlConfigPath: infra/telegraf.rendered.yaml

      - name: Map INFLUX_TOKEN to secretref after deploy
        shell: bash
        run: |
          az containerapp update -g "$RG" -n "$APP" \
            --set-env-vars INFLUX_TOKEN=secretref:influxdb-admin-token

      - name: Cleanup old inactive revisions
        shell: bash
        run: |
          az containerapp revision list -g "$RG" -n "$APP" \
            --query "[?properties.active==\`false\`].name" -o tsv | \
          xargs -r -I {} az containerapp revision delete -g "$RG" -n "$APP" --revision {} --yes
