name: OIDC Smoke Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sanity check repo for legacy auth
        shell: bash
        run: |
          echo "Scanning for 'auth-type'/'creds'/'AZURE_CREDENTIALS'..."
          (grep -RniE 'auth-type|creds:|AZURE_CREDENTIALS' .github/workflows && exit 1) || echo "OK"

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          # (Valfritt men ibland nödvändigt att T V I N G A ) 
          auth-type: id-token
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify
        run: az account show -o table
